# Generated by Django 3.2 on 2022-10-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_de',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_pl',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_ru',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='discription_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='discription_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='discription_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='discription_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='discription_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='discription_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='discription_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='discription_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='epoch_de',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='epoch_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='epoch_pl',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='epoch_ru',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='author_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='blog.author'),
        ),
        migrations.AddField(
            model_name='picture',
            name='author_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='blog.author'),
        ),
        migrations.AddField(
            model_name='picture',
            name='author_pl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='blog.author'),
        ),
        migrations.AddField(
            model_name='picture',
            name='author_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='blog.author'),
        ),
        migrations.AddField(
            model_name='picture',
            name='country_de',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='country_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='country_pl',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='country_ru',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='epoch_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='blog.epoch'),
        ),
        migrations.AddField(
            model_name='picture',
            name='epoch_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='blog.epoch'),
        ),
        migrations.AddField(
            model_name='picture',
            name='epoch_pl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='blog.epoch'),
        ),
        migrations.AddField(
            model_name='picture',
            name='epoch_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='blog.epoch'),
        ),
        migrations.AddField(
            model_name='picture',
            name='title_de',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='title_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='title_pl',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
