# Generated by Django 3.2 on 2022-11-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221009_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='height',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='length',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
