# Generated by Django 3.2 on 2023-02-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230228_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='year',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
